openapi: 3.1.0
info:
  title: Ultimate Bybit Spot Trading Assistant API
  version: "1.0"
  description: >
    Real-time crypto spot market assistant using Bybit, CoinGecko, Reddit sentiment, order book spread analysis,
    RSI momentum health scoring, whale signals, news sentiment, breakout strength, and volume divergence detection.

servers:
  - url: https://personaltradeassist-production.up.railway.app

paths:
  /sentiment:
    get:
      operationId: getSentiment
      summary: Get trending coins with full breakout diagnostics and sentiment analysis
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  fear_greed:
                    type: object
                    properties:
                      score:
                        type: integer
                      classification:
                        type: string
                  trending_coins:
                    type: array
                    items:
                      type: object
                      properties:
                        symbol:
                          type: string
                        current_price:
                          type: number
                        price_source:
                          type: string
                        reddit_mentions:
                          type: integer
                        signal:
                          type: string
                          enum: [BUY, CAUTION]
                        volatility_percent:
                          type: number
                        volatility_zone:
                          type: string
                        strategy_description:
                          type: string
                        bid_ask_spread_percent:
                          type: number
                        top_5_bids:
                          type: array
                          items:
                            type: object
                            properties:
                              price:
                                type: number
                              size:
                                type: number
                        top_5_asks:
                          type: array
                          items:
                            type: object
                            properties:
                              price:
                                type: number
                              size:
                                type: number
                        multi_timeframe_confirmation:
                          type: boolean
                        timeframes_status:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              price:
                                type: number
                              ema20:
                                type: number
                              trend:
                                type: string
                                enum: [bullish, bearish]
                        sector:
                          type: string
                        news_sentiment:
                          type: string
                          enum: [positive, neutral, negative]
                        social_dominance_spike:
                          type: boolean
                        active_address_spike:
                          type: boolean
                        whale_alert:
                          type: boolean
                        btc_inflow_spike:
                          type: boolean
                        rsi:
                          type: number
                        volume_divergence:
                          type: boolean
                        momentum_health:
                          type: string
                        breakout_score:
                          type: integer
                        time_estimate_to_tp:
                          type: string
                        buy_window_note:
                          type: string
                        scalp_entry:
                          type: number
                        scalp_tp:
                          type: number
                        scalp_sl:
                          type: number

  /market:
    get:
      operationId: getMarket
      summary: Get live Bybit Spot Market prices
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Spot price data returned

  /legal:
    get:
      operationId: getLegal
      summary: Legal disclaimer and usage policy
      responses:
        "200":
          description: Legal HTML disclaimer
          content:
            text/html:
              schema:
                type: string

  /health:
    get:
      operationId: getHealth
      summary: API health check
      responses:
        "200":
          description: Returns API health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
