openapi: 3.1.0
info:
  title: Personal Trade Assist API
  version: "1.2"
  description: >
    Provides crypto spot market analysis using Bybit, CoinGecko, Reddit, Fear & Greed Index,
    and internal calculations (volatility, spread, RSI, momentum, breakout scoring).
    Supports sentiment and scalp signals from precomputed data.

servers:
  - url: https://personaltradeassist-production.up.railway.app

paths:
  /sentiment:
    get:
      operationId: getSentiment
      summary: Get analyzed coins with sentiment and signals.
      responses:
        "200":
          description: Successfully returns analyzed sentiment data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  fear_greed:
                    type: object
                    properties:
                      score:
                        type: integer
                      classification:
                        type: string
                  trending_coins:
                    type: array
                    items:
                      $ref: '#/components/schemas/CoinAnalysis'
        "404":
          description: Data not yet initialized.

  /scalp-sentiment:
    get:
      operationId: getScalpSentiment
      summary: Get coins filtered for scalp trading.
      responses:
        "200":
          description: Returns filtered scalp opportunities.
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  strategy:
                    type: string
                  qualified_coins:
                    type: array
                    items:
                      $ref: '#/components/schemas/CoinAnalysis'
                  total_checked_in_full_run:
                    type: integer
                  total_qualified:
                    type: integer
        "503":
          description: Analysis data unavailable.

  /market:
    get:
      operationId: getMarket
      summary: Get Bybit Spot Market tickers.
      responses:
        "200":
          description: Returns Bybit market data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  data:
                    type: object
                    additionalProperties:
                      $ref: '#/components/schemas/BybitTicker'
        "503":
          description: Market data unavailable.

  /health:
    get:
      operationId: getHealth
      summary: Health check endpoint.
      responses:
        "200":
          description: Returns service health status.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok, initializing, stale_data]
                  last_basic_update:
                    type: string
                    format: date-time
                    nullable: true
                  last_full_update:
                    type: string
                    format: date-time
                    nullable: true

  /legal:
    get:
      operationId: getLegal
      summary: Legal disclaimer.
      responses:
        "200":
          description: Returns HTML disclaimer.
          content:
            text/html:
              schema:
                type: string

components:
  schemas:
    CoinAnalysis:
      type: object
      properties:
        symbol:
          type: string
        symbol_usdt:
          type: string
        current_price:
          type: number
        volume_24h:
          type: number
          nullable: true
        volatility_percent:
          type: number
          nullable: true
        volatility_zone:
          type: string
        strategy_suggestion:
          type: string
        bid_ask_spread_percent:
          type: number
          nullable: true
        multi_timeframe_confirmation:
          type: boolean
          nullable: true
        timeframes_status:
          type: object
          additionalProperties:
            type: object
            properties:
              price:
                type: number
                nullable: true
              ema20:
                type: number
                nullable: true
              trend:
                type: string
                enum: [bullish, bearish, unknown]
        rsi_1h:
          type: number
          nullable: true
        volume_divergence_1h:
          type: boolean
          nullable: true
        momentum_health:
          type: string
          enum: [strong, weak, oversold but healthy, neutral, unknown]
        breakout_score:
          type: integer
          nullable: true
        signal:
          type: string
          enum: [BUY, CAUTION, NEUTRAL, SELL/AVOID]
        time_estimate_to_tp:
          type: string
        sector:
          type: string
        reddit_mentions:
          type: integer
        news_sentiment:
          type: string
          enum: [positive, neutral, negative]
        fear_greed_context:
          type: string
        buy_window_note:
          type: string
        cg_metrics_source:
          type: string
        cg_slug:
          type: string
          nullable: true
        cg_sentiment_votes_up_percentage:
          type: number
          nullable: true
        cg_community_score:
          type: number
          nullable: true
        cg_developer_score:
          type: number
          nullable: true
        cg_public_interest_score:
          type: number
          nullable: true
        btc_inflow_spike:
          type: boolean
        orderbook_snapshot:
          type: object
          nullable: true
          properties:
            top_5_bids:
              type: array
              nullable: true
              items:
                type: object
            top_5_asks:
              type: array
              nullable: true
              items:
                type: object
            is_thin:
              type: boolean
        example_scalp_levels:
          type: object
          properties:
            entry_approx:
              type: number
            tp:
              type: number
            sl:
              type: number
        last_full_update:
          type: string
          format: date-time
        basic_update_timestamp:
          type: string
          format: date-time
          nullable: true

    BybitTicker:
      type: object
      properties:
        symbol:
          type: string
        lastPrice:
          type: string
        highPrice24h:
          type: string
          nullable: true
        lowPrice24h:
          type: string
          nullable: true
        prevPrice24h:
          type: string
          nullable: true
        price24hPcnt:
          type: string
          nullable: true
        volume24h:
          type: string
          nullable: true
        turnover24h:
          type: string
          nullable: true
        usdIndexPrice:
          type: string
          nullable: true
