openapi: 3.1.0
info:
  title: Ultimate Bybit Spot Trading Assistant API
  version: 1.0.0
  description: >
    Real-time crypto market and sentiment data for Bybit Spot. Includes volatility classification, Reddit signals,
    bid/ask spread tracking, and multi-timeframe EMA20 confirmation.

servers:
  - url: https://personaltradeassist-production.up.railway.app

paths:
  /sentiment:
    get:
      operationId: getSentiment
      summary: Get trending coin signals with sentiment, volatility, and technical alignment
      responses:
        '200':
          description: Full coin sentiment and analysis
          content:
            application/json:
              schema:
                type: object

  /market:
    get:
      operationId: getMarket
      summary: Get live Bybit Spot Market prices
      responses:
        '200':
          description: Live market price snapshot
          content:
            application/json:
              schema:
                type: object

  /legal:
    get:
      operationId: getLegal
      summary: Legal disclaimer and usage policy (HTML)
      responses:
        '200':
          description: Legal HTML page

  /health:
    get:
      operationId: getHealth
      summary: API healthcheck (for monitoring)
      responses:
        '200':
          description: Returns status: ok
